### PR TITLE
fix build on ghc 8.6

### PR DESCRIPTION
**Pull request by ra1u**
It fixes error regarding missing MonadFail instances 

```
src/Control/Monad/Bayes/Traced/Static.hs:78:5: error:
    • Could not deduce (MonadFail m)
        arising from a do statement
        with the failable pattern ‘x : xs’
      from the context: MonadSample m
        bound by the type signature for:
                   mh :: forall (m :: * -> *) a.
                         MonadSample m =>
                         Int -> Traced m a -> m [a]
        at src/Control/Monad/Bayes/Traced/Static.hs:73:1-49
      Possible fix:
        add (MonadFail m) to the context of
          the type signature for:
            mh :: forall (m :: * -> *) a.
                  MonadSample m =>
                  Int -> Traced m a -> m [a]
    • In a stmt of a 'do' block: x : xs <- f (k - 1)
      In the expression:
        do x : xs <- f (k - 1)
           y <- mhTrans m x
           return (y : x : xs)
      In an equation for ‘f’:
          f k
            = do x : xs <- f (k - 1)
                 y <- mhTrans m x
                 return (y : x : xs)
   |
78 |     x:xs <- f (k-1)
   |     ^^^^^^^^^^^^^^^
```

### CODE REVIEW

**Comment by curiousleo** [comment]
Thanks @ra1u! This issue has been fixed by https://github.com/tweag/monad-bayes/pull/54. `monad-bayes` now builds with recent GHC versions. Since the underlying issue has been resolved, I'll close this PR now.
